### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by haesleinhuepf** [bugraoezdemir/image_processing#2]
Hi @bugraoezdemir ,

I just found this repository and it seems super useful! I'm just wondering under which conditions it might be ok to re-use the tools and code. Would you mind adding a license file to the repository? If you're new to licensing, [read more](https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/).

Thanks!

Best,
Robert

**Comment by bugraoezdemir** [comment]
Hi @haesleinhuepf ,

I am happy to hear that you like the repository! I have just added a license file, and would be happy if you go ahead and reuse the code. Thanks a lot for the link about the licensing.

If you have any other recommendations or requests about the code, I would also be happy to hear them.

Thanks a lot!

Best,
Bugra

**Comment by haesleinhuepf** [comment]
Awesome, big thanks for the lightspeed response!
